# -*- coding: latin-1 -*-
"""
*******************************************************************************
** Script Name: tweet_articles.py
** Author(s):   Terrence Beach (tjbeachjr@gmail.com)
*******************************************************************************

** Description:

The script will take the tweets stored in a text file called new_tweets.txt, 
which was generated by the build_tweets_from_alerts.py script.

*******************************************************************************
"""
import codecs
import os
import sys
import time
import tweepy
sys.path.append("libs")
import common


###############################################################################
# Globals
###############################################################################

# The time to wait between tweets (in hours)
TWEET_SHIFT = 8

# The first tweet to be sent
TWEET_GREETING = "" 

# The last tweet to be sent
TWEET_SIGN_OFF = ""

# A list of stock tweets to inject inbetween article tweets
STOCK_TWEETS = []


###############################################################################
# Twitter account information for oAuthentication
###############################################################################

TWITTER_CONSUMER_KEY        = ""
TWITTER_CONSUMER_SECRET     = ""
TWITTER_ACCESS_TOKEN        = ""
TWITTER_ACCESS_TOKEN_SECRET = ""


###############################################################################
# Run the script when called from the command line
###############################################################################

def main():
    log = common.setup_logger("tweet_articles")
    
    # Log into the Twitter account
    log.info("Logging into Twitter account")
    auth = tweepy.OAuthHandler(TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET)
    auth.set_access_token(TWITTER_ACCESS_TOKEN, TWITTER_ACCESS_TOKEN_SECRET)
    twitter_api = tweepy.API(auth)

    # Get the list of articles to tweet (if any)
    if not os.path.exists("new_tweets.txt"):
        log.error("new_tweets.txt is missing.  Please run build_new_tweets.py script first.")
        return
    try:
        infile = codecs.open("new_tweets.txt", "r", "utf8")
    except:
        infile = open("new_tweets.txt", "r")
    articles = []
    for line in infile:
        article = line.rstrip()
        articles.append(article)
    
    # Build the list of tweets
    interval = len(articles) / len(STOCK_TWEETS)
    counter = 1
    tweets = []
    for article in articles:
        tweets.append(article)
        if counter == interval:
            if len(STOCK_TWEETS):
                tweets.append(STOCK_TWEETS.pop(0))
            counter = 1
        else:
            counter += 1
    tweets.append(TWEET_SIGN_OFF)
    
    # Tweet the articles
    send_tweet(log, twitter_api, "Sending Greeting - Tweet contents:", TWEET_GREETING)
    log.info("Sending %i new tweets" % len(tweets))
    counter = 1
    wait_time = TWEET_SHIFT * 3600 / len(tweets)
    for tweet in tweets:
        log.info("Waiting %i minutes before sending next tweet" % (wait_time / 60))
        time.sleep(wait_time)
        send_tweet(log, twitter_api, "Sending tweet %i - Tweet contents:" % counter, tweet)
        counter += 1


def send_tweet(log, twitter_api, message, tweet):
    retry = 0
    while True:
        if retry > 9:
            log.error("Maximum number of retries reached")
            return
        try:
            log.info(message)
            log.info(tweet)
            twitter_api.update_status(tweet)
            return
        except:
            log.error("Problem sending tweet. Retrying...")
            time.sleep(5.0)
            retry += 1

if __name__ == "__main__":
    main()